/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-06-20 13:53:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Checkout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import Control.TugurioSemplice.*;
import Model.*;
import Control.TugurioSemplice.Admin.*;
import java.util.*;
import Control.TugurioSemplice.*;
import Model.*;
import Control.TugurioSemplice.Admin.*;

public final class CartaCredito_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Home/footer.jsp", Long.valueOf(1749934775000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(10);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("Control.TugurioSemplice.Admin");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("Model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("Control.TugurioSemplice");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"it\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/screen.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/scrollbar.css\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;700;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <title>Pagamento con Carta di Credito</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<img src=\"photo/logo.png\" alt=\"logo\" class=\"logo\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <h2>Inserisci i dati della carta</h2>\n");
      out.write("\n");
      out.write("        ");

            CartaCreditoBean carta = (CartaCreditoBean) request.getAttribute("cartaCredito");
            boolean hasExistingCard = carta != null;
            
            String nomeIntestatario = "";
            String cognomeIntestatario = "";
            String numeroCarta = "";
            String dataScadenza = "";
            String rawCardNumber = "";

            if (hasExistingCard) {
                nomeIntestatario = carta.getNome() != null ? carta.getNome() : "";
                cognomeIntestatario = carta.getCognome() != null ? carta.getCognome() : "";
                rawCardNumber = carta.getNumeroCarta() != null ? carta.getNumeroCarta() : "";
                
                if (carta.getNumeroCarta() != null && carta.getNumeroCarta().length() == 16) {
                    String rawNumber = carta.getNumeroCarta();
                    numeroCarta = rawNumber.substring(0, 4) + " " +
                                  rawNumber.substring(4, 8) + " " +
                                  rawNumber.substring(8, 12) + " " +
                                  rawNumber.substring(12, 16);
                }

                if (carta.getScadenza() != null && carta.getScadenza().length() >= 5) {
                    String scadenzaCompleta = carta.getScadenza();
                    dataScadenza = scadenzaCompleta.substring(0, 2) + "/" + scadenzaCompleta.substring(scadenzaCompleta.length() - 2);
                }
            }
        
      out.write("\n");
      out.write("\n");
      out.write("        <form action=\"OrdineController\" method=\"post\">\n");
      out.write("            ");
 if (hasExistingCard) { 
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <p style=\"font-weight: bold;\">Stai utilizzando la carta registrata:</p>\n");
      out.write("                    <p>");
      out.print( nomeIntestatario );
      out.write(' ');
      out.print( cognomeIntestatario );
      out.write("</p>\n");
      out.write("                    <p>•••• •••• •••• ");
      out.print( rawCardNumber.substring(12) );
      out.write("</p>\n");
      out.write("                    <p>Scadenza: ");
      out.print( dataScadenza );
      out.write("</p>\n");
      out.write("                    \n");
      out.write("                    <input type=\"hidden\" name=\"nome\" value=\"");
      out.print( nomeIntestatario );
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"cognome\" value=\"");
      out.print( cognomeIntestatario );
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"numero\" value=\"");
      out.print( rawCardNumber );
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"scadenza\" value=\"");
      out.print( carta.getScadenza() );
      out.write("\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"cvv\">CVV *:</label>\n");
      out.write("                    <input type=\"text\" id=\"cvv\" name=\"cvv\" required \n");
      out.write("                           placeholder=\"3 cifre\" \n");
      out.write("                           maxlength=\"3\"\n");
      out.write("                           autocomplete=\"cc-csc\">\n");
      out.write("                    <small style=\"color: grey;\">Codice di sicurezza a 3 cifre sul retro della carta</small>\n");
      out.write("                </div>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"nome\">Nome intestatario *:</label>\n");
      out.write("                    <input type=\"text\" id=\"nome\" name=\"nome\" required \n");
      out.write("                           placeholder=\"Nome come appare sulla carta\" \n");
      out.write("                           value=\"");
      out.print( nomeIntestatario );
      out.write("\"\n");
      out.write("                           maxlength=\"50\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"cognome\">Cognome intestatario *:</label>\n");
      out.write("                    <input type=\"text\" id=\"cognome\" name=\"cognome\" required \n");
      out.write("                           placeholder=\"Cognome come appare sulla carta\" \n");
      out.write("                           value=\"");
      out.print( cognomeIntestatario );
      out.write("\"\n");
      out.write("                           maxlength=\"50\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"numero\">Numero carta *:</label>\n");
      out.write("                    <input type=\"text\" id=\"numero\" name=\"numero\" required \n");
      out.write("                           placeholder=\"XXXX XXXX XXXX XXXX\"\n");
      out.write("                           value=\"");
      out.print( numeroCarta );
      out.write("\"\n");
      out.write("                           maxlength=\"19\"\n");
      out.write("                           autocomplete=\"cc-number\">\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"scadenza\">Data scadenza *:</label>\n");
      out.write("                    <input type=\"text\" id=\"scadenza\" name=\"scadenza\" required \n");
      out.write("                           placeholder=\"MM/AA\" \n");
      out.write("                           maxlength=\"5\" \n");
      out.write("                           value=\"");
      out.print( dataScadenza );
      out.write("\"\n");
      out.write("                           autocomplete=\"cc-exp\">\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"cvv\">CVV *:</label>\n");
      out.write("                    <input type=\"text\" id=\"cvv\" name=\"cvv\" required \n");
      out.write("                           placeholder=\"3 cifre\" \n");
      out.write("                           maxlength=\"3\"\n");
      out.write("                           autocomplete=\"cc-csc\">\n");
      out.write("                    <small style=\"color: grey;\">Codice di sicurezza a 3 cifre sul retro della carta</small>\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            <input type=\"hidden\" name=\"pagamento\" value=\"Carta\">\n");
      out.write("            <input id=\"spedizione\" type=\"hidden\" name=\"spedizione\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${spedizione}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <small style=\"color: grey;\">\n");
      out.write("                    <strong>Informazioni sulla sicurezza:</strong><br>\n");
      out.write("                    • I tuoi dati sono protetti con crittografia SSL<br>\n");
      out.write("                    • Tutti i campi contrassegnati con * sono obbligatori\n");
      out.write("                </small>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <button type=\"submit\" class=\"submit-btn\">Conferma pagamento</button>\n");
      out.write("        </form>\n");
      out.write("        \n");
      out.write("        <div style=\"margin-top: 20px;\">\n");
      out.write("            <a href=\"./cart.jsp\" style=\"text-decoration: none;\">\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"it\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/footer.css\">\n");
      out.write("		<link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;700;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("        <title>TugurioSemplice - Home</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("       <footer class=\"footer-container\">\n");
      out.write("    <div class=\"footer-links\">\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/ChiSiamo.jsp\" title=\"Informazioni su di noi\">Chi siamo</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/PrivacyPolicy.jsp\" title=\"La nostra politica sulla privacy\">Privacy Policy</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/TerminiCondizioni.jsp\" title=\"Termini del servizio\">Termini e Condizioni</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/Contatti.jsp\" title=\"Contattaci\">Contatti</a>\n");
      out.write("    </div>\n");
      out.write("    <p class=\"text copyright\">&copy; 2025 TugurioSemplice. Tutti i diritti riservati.</p>\n");
      out.write("</footer>\n");
      out.write("    </body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("    <script src=\"/TugurioSemplice/JavaScript/CartaCredito.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
