/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-06-18 06:53:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Checkout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import Control.TugurioSemplice.*;
import Model.*;
import Control.TugurioSemplice.Admin.*;
import java.util.*;
import Control.TugurioSemplice.*;
import Model.*;
import Control.TugurioSemplice.Admin.*;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Home/footer.jsp", Long.valueOf(1749934775000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(10);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("Control.TugurioSemplice.Admin");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("Model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("Control.TugurioSemplice");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"it\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/checkout.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/scrollbar.css\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;700;900&display=swap\" rel=\"stylesheet\"> 	\n");
      out.write("    <title>TugurioSemplice - Checkout</title>\n");
      out.write("    \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<img src=\"photo/logo.png\" alt=\"logo\" class=\"logo\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <h1>Completa il tuo ordine</h1>\n");
      out.write("        \n");
      out.write("        <div class=\"checkout-section\">\n");
      out.write("            <div class=\"checkout-form\">\n");
      out.write("                <div class=\"user-info\">\n");
      out.write("    				<h2>Informazioni personali</h2>\n");
      out.write("    				");
 
    					ClienteBean user = (ClienteBean) request.getAttribute("user");
    				
      out.write("\n");
      out.write("        			<p>");
      out.print( user.getAnagrafia().getNome() );
      out.write(' ');
      out.print( user.getAnagrafia().getCognome() );
      out.write("</p>\n");
      out.write("        			<p>");
      out.print( user.getEmail() );
      out.write("</p>\n");
      out.write("        			<p>");
      out.print( user.getIndirizzoSpedizione());
      out.write("</p>\n");
      out.write("				</div>    \n");
      out.write("                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/PagamentoController\" method=\"post\" class=\"payment-section\">\n");
      out.write("                    <h2>Metodo di pagamento</h2>\n");
      out.write("                    \n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"pagamento\">Scegli il pagamento</label>\n");
      out.write("                        <select id=\"pagamento\" name=\"pagamento\" required>\n");
      out.write("                            <option value=\"\">-- Seleziona --</option>\n");
      out.write("                            <option value=\"Carta\">Carta di credito</option>\n");
      out.write("                            <option value=\"Contanti\">Contanti al tabacchino</option>\n");
      out.write("                        </select>\n");
      out.write("                    </div>      \n");
      out.write("               		<div class=\"form-group\">\n");
      out.write("                		<label for=\"spedizione\">Scegli il metodo di spedizione *:</label>\n");
      out.write("                			<select id=\"spedizione\" name=\"spedizione\" required>\n");
      out.write("			                    <option value=\"\">-- Seleziona metodo di spedizione --</option>\n");
      out.write("			                    <option value=\"Trasporto funebre\">Trasporto funebre</option>\n");
      out.write("			                    <option value=\"Consegna a domicilio\">Consegna a domicilio</option>\n");
      out.write("			                    <option value=\"Ritiro in negozio\">Ritiro in negozio</option>\n");
      out.write("		                	</select>\n");
      out.write("            		</div>                                     \n");
      out.write("                    <button type=\"submit\">Conferma ordine</button>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("			<div class=\"order-summary\">\n");
      out.write("			    <h2>Riepilogo ordine</h2>\n");
      out.write("			    ");
 
				    List<ProdottoBean> cartItems = (List<ProdottoBean>) request.getAttribute("cartItems");
				    Map<Integer, Integer> quantities = (Map<Integer, Integer>) request.getAttribute("quantities");
				    Double totalAmount = (Double) request.getAttribute("totalAmount");
				    
				    if (cartItems != null && !cartItems.isEmpty()) {
				        for (ProdottoBean product : cartItems) {
				            int quantity = quantities.get(product.getIdProdotto());
			    
      out.write("\n");
      out.write("			    <div class=\"order-item\">\n");
      out.write("			    <div>\n");
      out.write("			    	");
      out.print( product.getNome() );
      out.write(' ');
      out.write('x');
      out.write(' ');
      out.print( quantity );
      out.write("\n");
      out.write("			    </div>\n");
      out.write("			    <div>\n");
      out.write("			    	€ ");
      out.print( String.format("%.2f", product.getPrezzoBase() * quantity) );
      out.write("</div>\n");
      out.write("			    </div>\n");
      out.write("			    ");
 
			        }
			    
      out.write("\n");
      out.write("			    <div class=\"total\">\n");
      out.write("			    	<div>Totale:</div>\n");
      out.write("			        <div>€ ");
      out.print( String.format("%.2f", totalAmount) );
      out.write("</div>\n");
      out.write("			    </div>\n");
      out.write("			    ");
 } else { 
      out.write("\n");
      out.write("			        <p>Il carrello è vuoto.</p>\n");
      out.write("			    ");
 } 
      out.write("\n");
      out.write("			</div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"it\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/footer.css\">\n");
      out.write("		<link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;700;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("        <title>TugurioSemplice - Home</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("       <footer class=\"footer-container\">\n");
      out.write("    <div class=\"footer-links\">\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/ChiSiamo.jsp\" title=\"Informazioni su di noi\">Chi siamo</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/PrivacyPolicy.jsp\" title=\"La nostra politica sulla privacy\">Privacy Policy</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/TerminiCondizioni.jsp\" title=\"Termini del servizio\">Termini e Condizioni</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/Contatti.jsp\" title=\"Contattaci\">Contatti</a>\n");
      out.write("    </div>\n");
      out.write("    <p class=\"text copyright\">&copy; 2025 TugurioSemplice. Tutti i diritti riservati.</p>\n");
      out.write("</footer>\n");
      out.write("    </body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("    \n");
      out.write("    <!-- Script per riordinare la sezione pagamento su mobile -->\n");
      out.write("    <script>\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("        const paymentSection = document.querySelector('.payment-section');\n");
      out.write("        const checkoutSection = document.querySelector('.checkout-section');\n");
      out.write("        const checkoutForm = document.querySelector('.checkout-form');\n");
      out.write("        \n");
      out.write("        function movePaymentSection() {\n");
      out.write("            if (window.innerWidth <= 768) {\n");
      out.write("                // In modalità mobile, sposta al fondo del checkout section\n");
      out.write("                checkoutSection.appendChild(paymentSection);\n");
      out.write("            } else {\n");
      out.write("                // In modalità desktop, rimetti nella checkout form\n");
      out.write("                checkoutForm.appendChild(paymentSection);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        // Esegui all'inizio e al ridimensionamento\n");
      out.write("        movePaymentSection();\n");
      out.write("        window.addEventListener('resize', movePaymentSection);\n");
      out.write("    });\n");
      out.write("    </script>               \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
