/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-06-18 06:54:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import Control.TugurioSemplice.*;
import Model.*;
import Control.TugurioSemplice.Admin.*;
import java.util.*;
import Control.TugurioSemplice.*;
import Model.*;
import Control.TugurioSemplice.Admin.*;
import java.util.*;
import Control.TugurioSemplice.*;
import Model.*;
import Control.TugurioSemplice.Admin.*;

public final class ChiSiamo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Home/header.jsp", Long.valueOf(1749934793000L));
    _jspx_dependants.put("/Home/footer.jsp", Long.valueOf(1749934775000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(10);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("Control.TugurioSemplice.Admin");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("Model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("Control.TugurioSemplice");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"it\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/ChiSiamo.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/scrollbar.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;700;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <title>Chi Siamo - Tugurio Semplice</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"it\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/header.css\">\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;400;700;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\n");
      out.write("        <title>TugurioSemplice - Home</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("    ");
 ClienteBean utente = (ClienteBean) session.getAttribute("user"); 
      out.write("\n");
      out.write("        <header class=\"menu\">\n");
      out.write("            <div class=\"top-bar\">\n");
      out.write("                <button class=\"mobile-menu\" aria-label=\"Toggle menu\">\n");
      out.write("                    <i class=\"fas fa-bars\"></i>\n");
      out.write("                    <i class=\"fas fa-times\"></i>\n");
      out.write("                </button>\n");
      out.write("                <span class=\"logo-text\">TUGURIOSEMPLICE</span>\n");
      out.write("                <a class=\"logo-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/logo.png\" alt=\"TugurioSemplice Logo\">\n");
      out.write("                </a>\n");
      out.write("                ");
 if(utente != null) { 
      out.write("\n");
      out.write("                <a class=\"login-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AuthSites/AreaUtente.jsp\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/Connesso.jpg\" alt=\"login\">\n");
      out.write("                </a>\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                <a class=\"login-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AccessoUtente/Login.jsp\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/access.png\" alt=\"login\">\n");
      out.write("                </a>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                <a class=\"cart-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart.jsp\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/cart.png\" alt=\"carrello\">\n");
      out.write("                </a>\n");
      out.write("            </div>  \n");
      out.write("            <nav id=\"main-nav\">  \n");
      out.write("    <a class=\"menu-item ");
      out.print( request.getRequestURI().contains("index.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">HOME</a>\n");
      out.write("    <a class=\"menu-item ");
      out.print( request.getRequestURI().contains("about.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/ChiSiamo.jsp\">CHI SIAMO</a>\n");
      out.write("    <a class=\"menu-item ");
      out.print( request.getRequestURI().contains("ProductView.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product\">CATALOGO</a>\n");
      out.write("    <a class=\"menu-item ");
      out.print( request.getRequestURI().contains("contact.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/Contatti.jsp\">CONTATTI</a>\n");
      out.write("    ");
 if(utente != null) { 
      out.write("\n");
      out.write("    <a class=\"menu-item mobile-only ");
      out.print( request.getRequestURI().contains("AreaUtente.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AreaUtente.jsp\">AREA UTENTE</a>\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("    <a class=\"menu-item mobile-only ");
      out.print( request.getRequestURI().contains("Login.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AuthSites/Login.jsp\">ACCEDI</a>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    <a class=\"menu-item mobile-only ");
      out.print( request.getRequestURI().contains("cart.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart.jsp\">CARRELLO</a>\n");
      out.write("</nav>\n");
      out.write("        </header>\n");
      out.write("        \n");
      out.write("        <script>\n");
      out.write("            document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("                const mobileMenuToggle = document.querySelector('.mobile-menu');\n");
      out.write("                const mainNav = document.getElementById('main-nav');\n");
      out.write("                \n");
      out.write("                mobileMenuToggle.addEventListener('click', function() {\n");
      out.write("                this.classList.toggle('active');\n");
      out.write("                mainNav.classList.toggle('mobile-active');\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("    </body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<div class=\"main-content\">\r\n");
      out.write("        <h1>Chi Siamo - La Nostra Storia, la Nostra Missione</h1>\r\n");
      out.write("        <p class=\"p-with-divider\">\r\n");
      out.write("            Benvenuti a TugurioSemplice, il punto di riferimento per gli amanti del buon gusto e dell'autenticità.\r\n");
      out.write("            Siamo nati dalla passione per l'eccellenza culinaria e l'amore per i prodotti di qualità, con l'obiettivo\r\n");
      out.write("            di portare la migliore selezione di bar nel comfort della vostra casa. Crediamo che ogni pasto debba essere\r\n");
      out.write("            un'esperienza, e per questo ci impegniamo a selezionare solo i migliori ingredienti e a collaborare con i\r\n");
      out.write("            produttori più affidabili e attenti al dettaglio. La nostra missione è rendere la vendita di bar semplice,\r\n");
      out.write("            accessibile e deliziosa per tutti, garantendo freschezza, qualità e un servizio clienti impeccabile.\r\n");
      out.write("            Unisciti a noi in questo viaggio di sapori e scopri il vero piacere del cibo di qualità, senza complicazioni.\r\n");
      out.write("        </p>\r\n");
      out.write("        \r\n");
      out.write("        <h2>I Nostri Fondatori e Partner Speciali</h2>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"founders-container\">\r\n");
      out.write("            <div class=\"founder-section\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/tugulander.png\" alt=\"Carmine de Fieto\">\r\n");
      out.write("                <div class=\"founder-content\">\r\n");
      out.write("                    <h3>JOHN</h3>\r\n");
      out.write("                    <p>\r\n");
      out.write("                        Da oltre trent’anni, John dedica la sua vita a offrire sostegno e rispetto a chi affronta un momento difficile. \r\n");
      out.write("                        Ha fondato la nostra impresa con un principio semplice: accompagnare ogni famiglia con discrezione, \r\n");
      out.write("                        professionalità e umanità. È il punto di riferimento per clienti e colleghi, grazie alla sua esperienza e \r\n");
      out.write("                        alla sua profonda sensibilità.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"founder-section\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/abisso.png\" alt=\"Aldo Glass\">\r\n");
      out.write("                <div class=\"founder-content\">\r\n");
      out.write("                    <h3>GIORGIO</h3>\r\n");
      out.write("                    <p>\r\n");
      out.write("                        Preciso, empatico e sempre presente, Giorgio si occupa dell’organizzazione delle cerimonie funebri in ogni dettaglio. \r\n");
      out.write("                        Dalla scelta del rito alle esigenze della famiglia, è lui a garantire che tutto si svolga con ordine e rispetto. \r\n");
      out.write("                        Con un approccio umano e discreto, è il volto sereno su cui contare nei momenti più delicati.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"founder-section\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/a-tugurio.png\" alt=\"Movieplex Mercogliano\">\r\n");
      out.write("                <div class=\"founder-content\">\r\n");
      out.write("                    <h3>JAMAL</h3>\r\n");
      out.write("                    <p>\r\n");
      out.write("                        Jaml è il cuore logistico della nostra impresa. Con competenza e riservatezza, si occupa dei trasporti, \r\n");
      out.write("                        della preparazione e della gestione tecnica dei servizi funebri. Il suo ruolo, spesso dietro le quinte, \r\n");
      out.write("                        è essenziale per assicurare che ogni cerimonia si svolga con dignità e precisione.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"founder-section\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/butcher.png\" alt=\"Dolci Tentazioni\">\r\n");
      out.write("                <div class=\"founder-content\">\r\n");
      out.write("                    <h3>BUTCHER</h3>\r\n");
      out.write("                    <p>\r\n");
      out.write("                        Accogliere, ascoltare, accompagnare: queste sono le parole che guidano il lavoro di Butcher. \r\n");
      out.write("                        È lui a offrire il primo contatto, a comprendere le necessità di chi ha appena perso una persona cara \r\n");
      out.write("                        e a trovare insieme la soluzione più adatta, sempre nel rispetto della volontà e dei valori della famiglia.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"it\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/footer.css\">\n");
      out.write("		<link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;700;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("        <title>TugurioSemplice - Home</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("       <footer class=\"footer-container\">\n");
      out.write("    <div class=\"footer-links\">\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/ChiSiamo.jsp\" title=\"Informazioni su di noi\">Chi siamo</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/PrivacyPolicy.jsp\" title=\"La nostra politica sulla privacy\">Privacy Policy</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/TerminiCondizioni.jsp\" title=\"Termini del servizio\">Termini e Condizioni</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/Contatti.jsp\" title=\"Contattaci\">Contatti</a>\n");
      out.write("    </div>\n");
      out.write("    <p class=\"text copyright\">&copy; 2025 TugurioSemplice. Tutti i diritti riservati.</p>\n");
      out.write("</footer>\n");
      out.write("    </body>\n");
      out.write("</html>");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
