/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-06-18 06:54:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import Control.TugurioSemplice.*;
import Model.*;
import Control.TugurioSemplice.Admin.*;
import java.util.*;
import Control.TugurioSemplice.*;
import Model.*;
import Control.TugurioSemplice.Admin.*;
import java.util.*;
import Control.TugurioSemplice.*;
import Model.*;
import Control.TugurioSemplice.Admin.*;

public final class Contatti_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Home/header.jsp", Long.valueOf(1749934793000L));
    _jspx_dependants.put("/Home/footer.jsp", Long.valueOf(1749934775000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(10);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("Control.TugurioSemplice.Admin");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("Model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("Control.TugurioSemplice");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"it\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/Contatti.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/scrollbar.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;700;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <title>Contatti - Tugurio Semplice</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"it\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/header.css\">\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;400;700;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\n");
      out.write("        <title>TugurioSemplice - Home</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("    ");
 ClienteBean utente = (ClienteBean) session.getAttribute("user"); 
      out.write("\n");
      out.write("        <header class=\"menu\">\n");
      out.write("            <div class=\"top-bar\">\n");
      out.write("                <button class=\"mobile-menu\" aria-label=\"Toggle menu\">\n");
      out.write("                    <i class=\"fas fa-bars\"></i>\n");
      out.write("                    <i class=\"fas fa-times\"></i>\n");
      out.write("                </button>\n");
      out.write("                <span class=\"logo-text\">TUGURIOSEMPLICE</span>\n");
      out.write("                <a class=\"logo-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/logo.png\" alt=\"TugurioSemplice Logo\">\n");
      out.write("                </a>\n");
      out.write("                ");
 if(utente != null) { 
      out.write("\n");
      out.write("                <a class=\"login-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AuthSites/AreaUtente.jsp\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/Connesso.jpg\" alt=\"login\">\n");
      out.write("                </a>\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                <a class=\"login-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AccessoUtente/Login.jsp\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/access.png\" alt=\"login\">\n");
      out.write("                </a>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                <a class=\"cart-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart.jsp\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/cart.png\" alt=\"carrello\">\n");
      out.write("                </a>\n");
      out.write("            </div>  \n");
      out.write("            <nav id=\"main-nav\">  \n");
      out.write("    <a class=\"menu-item ");
      out.print( request.getRequestURI().contains("index.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">HOME</a>\n");
      out.write("    <a class=\"menu-item ");
      out.print( request.getRequestURI().contains("about.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/ChiSiamo.jsp\">CHI SIAMO</a>\n");
      out.write("    <a class=\"menu-item ");
      out.print( request.getRequestURI().contains("ProductView.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product\">CATALOGO</a>\n");
      out.write("    <a class=\"menu-item ");
      out.print( request.getRequestURI().contains("contact.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/Contatti.jsp\">CONTATTI</a>\n");
      out.write("    ");
 if(utente != null) { 
      out.write("\n");
      out.write("    <a class=\"menu-item mobile-only ");
      out.print( request.getRequestURI().contains("AreaUtente.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AreaUtente.jsp\">AREA UTENTE</a>\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("    <a class=\"menu-item mobile-only ");
      out.print( request.getRequestURI().contains("Login.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AuthSites/Login.jsp\">ACCEDI</a>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    <a class=\"menu-item mobile-only ");
      out.print( request.getRequestURI().contains("cart.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart.jsp\">CARRELLO</a>\n");
      out.write("</nav>\n");
      out.write("        </header>\n");
      out.write("        \n");
      out.write("        <script>\n");
      out.write("            document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("                const mobileMenuToggle = document.querySelector('.mobile-menu');\n");
      out.write("                const mainNav = document.getElementById('main-nav');\n");
      out.write("                \n");
      out.write("                mobileMenuToggle.addEventListener('click', function() {\n");
      out.write("                this.classList.toggle('active');\n");
      out.write("                mainNav.classList.toggle('mobile-active');\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("    </body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<div class=\"main-content\">\r\n");
      out.write("        <h1>Contatti - Siamo Sempre al Vostro Fianco</h1>\r\n");
      out.write("        <p class=\"p-with-divider\">\r\n");
      out.write("            Nel momento del dolore, sappiamo quanto sia importante avere un punto di riferimento sicuro e disponibile.\r\n");
      out.write("            Il nostro team è sempre pronto ad accogliervi con rispetto, discrezione e professionalità. Contattateci\r\n");
      out.write("            in qualsiasi momento: siamo qui per accompagnarvi con sensibilità e competenza in ogni fase del servizio funebre,\r\n");
      out.write("            offrendo supporto personalizzato per onorare la memoria dei vostri cari nel modo più dignitoso possibile.\r\n");
      out.write("        </p>\r\n");
      out.write("        \r\n");
      out.write("        <h2>Come Raggiungerci</h2>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"contact-container\">\r\n");
      out.write("            <div class=\"contact-section\">\r\n");
      out.write("                <div class=\"contact-icon\">\r\n");
      out.write("                    <svg width=\"60\" height=\"60\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#74292c\" stroke-width=\"2\">\r\n");
      out.write("                        <path d=\"M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"contact-content\">\r\n");
      out.write("                    <h3>TELEFONO</h3>\r\n");
      out.write("                    <p class=\"contact-main\">+39 081 123 4567</p>\r\n");
      out.write("                    <p class=\"contact-sub\">Reperibili 24 ore su 24, 7 giorni su 7</p>\r\n");
      out.write("                    <p class=\"contact-desc\">\r\n");
      out.write("                        Il nostro servizio telefonico è sempre attivo per garantirvi assistenza immediata.\r\n");
      out.write("                        Non esitate a chiamarci in qualsiasi momento del giorno o della notte.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"contact-section\">\r\n");
      out.write("                <div class=\"contact-icon\">\r\n");
      out.write("                    <svg width=\"60\" height=\"60\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#74292c\" stroke-width=\"2\">\r\n");
      out.write("                        <path d=\"M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z\"/>\r\n");
      out.write("                        <circle cx=\"12\" cy=\"10\" r=\"3\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"contact-content\">\r\n");
      out.write("                    <h3>SEDE PRINCIPALE</h3>\r\n");
      out.write("                    <p class=\"contact-main\">Via Roma, 123</p>\r\n");
      out.write("                    <p class=\"contact-sub\">80100 Napoli (NA)</p>\r\n");
      out.write("                    <p class=\"contact-desc\">\r\n");
      out.write("                        La nostra sede principale vi accoglie in un ambiente riservato e confortevole,\r\n");
      out.write("                        dove potrete parlare con i nostri esperti e pianificare ogni dettaglio del servizio.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"contact-section\">\r\n");
      out.write("                <div class=\"contact-icon\">\r\n");
      out.write("                    <svg width=\"60\" height=\"60\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#74292c\" stroke-width=\"2\">\r\n");
      out.write("                        <path d=\"M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z\"/>\r\n");
      out.write("                        <polyline points=\"22,6 12,13 2,6\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"contact-content\">\r\n");
      out.write("                    <h3>EMAIL</h3>\r\n");
      out.write("                    <p class=\"contact-main\">info@tugurio-semplice.it</p>\r\n");
      out.write("                    <p class=\"contact-sub\">Risposta entro 2 ore</p>\r\n");
      out.write("                    <p class=\"contact-desc\">\r\n");
      out.write("                        Per informazioni, preventivi o richieste particolari, scriveteci via email.\r\n");
      out.write("                        Il nostro team risponderà tempestivamente ad ogni vostra richiesta.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"contact-section\">\r\n");
      out.write("                <div class=\"contact-icon\">\r\n");
      out.write("                    <svg width=\"60\" height=\"60\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#74292c\" stroke-width=\"2\">\r\n");
      out.write("                        <circle cx=\"12\" cy=\"12\" r=\"10\"/>\r\n");
      out.write("                        <polyline points=\"12,6 12,12 16,14\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"contact-content\">\r\n");
      out.write("                    <h3>ORARI UFFICIO</h3>\r\n");
      out.write("                    <p class=\"contact-main\">Lunedì - Venerdì: 8:00 - 18:00</p>\r\n");
      out.write("                    <p class=\"contact-sub\">Sabato: 8:00 - 13:00</p>\r\n");
      out.write("                    <p class=\"contact-desc\">\r\n");
      out.write("                        I nostri uffici sono aperti per consulenze e appuntamenti. Il servizio di reperibilità\r\n");
      out.write("                        telefonica rimane attivo anche al di fuori di questi orari.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"emergency-section\">\r\n");
      out.write("            <h2>Servizio di Emergenza</h2>\r\n");
      out.write("            <div class=\"emergency-content\">\r\n");
      out.write("                <div class=\"emergency-icon\">\r\n");
      out.write("                    <svg width=\"60\" height=\"60\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"white\" stroke-width=\"2.5\">\r\n");
      out.write("                        <path d=\"M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"emergency-text\">\r\n");
      out.write("                <br><br>\r\n");
      out.write("                    <h3>NUMERO DI EMERGENZA</h3>\r\n");
      out.write("                    <p class=\"emergency-number\">+39 333 999 8877</p>\r\n");
      out.write("                    <p>\r\n");
      out.write("                        In caso di necessità urgenti al di fuori degli orari di ufficio, questo numero vi metterà\r\n");
      out.write("                        immediatamente in contatto con il nostro responsabile di turno. Garantiamo intervento rapido\r\n");
      out.write("                        e assistenza completa in qualsiasi momento della giornata.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"it\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/footer.css\">\n");
      out.write("		<link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;700;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("        <title>TugurioSemplice - Home</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("       <footer class=\"footer-container\">\n");
      out.write("    <div class=\"footer-links\">\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/ChiSiamo.jsp\" title=\"Informazioni su di noi\">Chi siamo</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/PrivacyPolicy.jsp\" title=\"La nostra politica sulla privacy\">Privacy Policy</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/TerminiCondizioni.jsp\" title=\"Termini del servizio\">Termini e Condizioni</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/Contatti.jsp\" title=\"Contattaci\">Contatti</a>\n");
      out.write("    </div>\n");
      out.write("    <p class=\"text copyright\">&copy; 2025 TugurioSemplice. Tutti i diritti riservati.</p>\n");
      out.write("</footer>\n");
      out.write("    </body>\n");
      out.write("</html>");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
