/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-06-21 13:11:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import Control.TugurioSemplice.*;
import Model.*;
import Control.TugurioSemplice.Admin.*;
import Control.Filtri.*;

public final class Fattura_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(11);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("Control.TugurioSemplice.Admin");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("Model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("Control.TugurioSemplice");
    _jspx_imports_packages.add("Control.Filtri");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

OrdineBean ordine = (OrdineBean) request.getAttribute("ordine");
ArrayList<Map<String, Object>> dettagliOrdine = (ArrayList<Map<String, Object>>) request.getAttribute("dettagliOrdine");
PagamentoBean pagamento = (PagamentoBean) request.getAttribute("pagamento");
SpedizioneBean spedizione = (SpedizioneBean) request.getAttribute("spedizione");
ClienteBean utente = (ClienteBean) session.getAttribute("user");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/Utente.css\">\n");
      out.write("    	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/scrollbar.css\">\n");
      out.write("		<link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;400;700;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <title>Fattura - FAT-");
      out.print( ordine.getIdOrdine() );
      out.write("</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("        <div class=\"main-container\">\n");
      out.write("            <!-- Header -->\n");
      out.write("            <div class=\"page-header\">\n");
      out.write("            <br>\n");
      out.write("                <h1>Fattura</h1>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"content\">\n");
      out.write("                <!-- Invoice Info -->\n");
      out.write("                <div class=\"data-section\">\n");
      out.write("                    <h3>Informazioni Fattura</h3>\n");
      out.write("                    <div class=\"data-item\">\n");
      out.write("                        <span class=\"data-label\">Numero Fattura:</span>\n");
      out.write("                        <span class=\"data-value\">FAT-");
      out.print( ordine.getIdOrdine() );
      out.write("</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"data-item\">\n");
      out.write("                        <span class=\"data-label\">Data:</span>\n");
      out.write("                        <span class=\"data-value\">");
      out.print( ordine.getDataOrdine() );
      out.write("</span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Seller Info -->\n");
      out.write("                <div class=\"data-section\">\n");
      out.write("                    <h3>Venditore</h3>\n");
      out.write("                    <div class=\"data-item\">\n");
      out.write("                        <span class=\"data-label\">Ragione Sociale:</span>\n");
      out.write("                        <span class=\"data-value\">Tugurio Semplice S.r.l.</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"data-item\">\n");
      out.write("                        <span class=\"data-label\">Indirizzo:</span>\n");
      out.write("                        <span class=\"data-value\">Via Esempio, 123</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"data-item\">\n");
      out.write("                        <span class=\"data-label\">Città:</span>\n");
      out.write("                        <span class=\"data-value\">00123 Roma (RM)</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"data-item\">\n");
      out.write("                        <span class=\"data-label\">P.IVA:</span>\n");
      out.write("                        <span class=\"data-value\">12345678901</span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Customer Info -->\n");
      out.write("                <div class=\"data-section\">\n");
      out.write("                    <h3>Cliente</h3>\n");
      out.write("                    <div class=\"data-item\">\n");
      out.write("                        <span class=\"data-label\">Nome:</span>\n");
      out.write("                        <span class=\"data-value\">\n");
      out.write("                            ");
      out.print( utente.getAnagrafia() != null ? utente.getAnagrafia().getNome() + " " + utente.getAnagrafia().getCognome() : "N/D" );
      out.write("\n");
      out.write("                        </span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"data-item\">\n");
      out.write("                        <span class=\"data-label\">Codice Fiscale:</span>\n");
      out.write("                        <span class=\"data-value\">\n");
      out.write("                            ");
      out.print( utente.getAnagrafia() != null ? utente.getAnagrafia().getCf() : "N/D" );
      out.write("\n");
      out.write("                        </span>\n");
      out.write("                    </div>\n");
      out.write("                    ");
 if(utente.getIndirizzoSpedizione() != null) { 
      out.write("\n");
      out.write("                        <div class=\"data-item\">\n");
      out.write("                            <span class=\"data-label\">Indirizzo:</span>\n");
      out.write("                            <span class=\"data-value\">");
      out.print( utente.getIndirizzoSpedizione().getVia() );
      out.write("</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"data-item\">\n");
      out.write("                            <span class=\"data-label\">Città:</span>\n");
      out.write("                            <span class=\"data-value\">\n");
      out.write("                                ");
      out.print( utente.getIndirizzoSpedizione().getCitta() );
      out.write(' ');
      out.write('(');
      out.print( utente.getIndirizzoSpedizione().getProvincia() );
      out.write(")\n");
      out.write("                            </span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"data-item\">\n");
      out.write("                            <span class=\"data-label\">CAP:</span>\n");
      out.write("                            <span class=\"data-value\">");
      out.print( utente.getIndirizzoSpedizione().getCap() );
      out.write("</span>\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } else { 
      out.write("\n");
      out.write("                        <div class=\"data-item\">\n");
      out.write("                            <span class=\"data-label\">Indirizzo:</span>\n");
      out.write("                            <span class=\"data-value\">N/D</span>\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Order Details -->\n");
      out.write("                <div class=\"order-section\">\n");
      out.write("                    <h3>Dettagli Ordine</h3>\n");
      out.write("                    ");

                    double subtotale = 0;
                    if(dettagliOrdine != null && !dettagliOrdine.isEmpty()) {
                        for(Map<String, Object> dettaglio : dettagliOrdine) {
                            String nomeProdotto = (String) dettaglio.get("nomeProdotto");
                            int quantita = (Integer) dettaglio.get("quantita");
                            double prezzo = (Double) dettaglio.get("prezzo");
                            double totaleRiga = quantita * prezzo;
                            subtotale += totaleRiga;
                    
      out.write("\n");
      out.write("                        <div class=\"order-subsection\">\n");
      out.write("                            <div class=\"product-item\">\n");
      out.write("                                <div class=\"data-item\">\n");
      out.write("                                    <span class=\"data-label\">Articolo:</span>\n");
      out.write("                                    <span class=\"data-value\">");
      out.print( nomeProdotto );
      out.write("</span>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"data-item\">\n");
      out.write("                                    <span class=\"data-label\">Quantità:</span>\n");
      out.write("                                    <span class=\"data-value\">");
      out.print( quantita );
      out.write("</span>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"data-item\">\n");
      out.write("                                    <span class=\"data-label\">Prezzo Unitario:</span>\n");
      out.write("                                    <span class=\"data-value\">");
      out.print( String.format("%.2f", prezzo) );
      out.write(" €</span>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"data-item\">\n");
      out.write("                                    <span class=\"data-label\">Totale:</span>\n");
      out.write("                                    <span class=\"data-value\">");
      out.print( String.format("%.2f", totaleRiga) );
      out.write(" €</span>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    ");
 
                        }
                    } else {
                    
      out.write("\n");
      out.write("                        <div class=\"no-data-message\">\n");
      out.write("                            Nessun dettaglio ordine disponibile\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                    \n");
      out.write("                    <div class=\"order-subsection\">\n");
      out.write("                        <div class=\"data-item\">\n");
      out.write("                            <span class=\"data-label\">SUBTOTALE:</span>\n");
      out.write("                            <span class=\"data-value\">");
      out.print( String.format("%.2f", subtotale) );
      out.write(" €</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Payment Info -->\n");
      out.write("                ");
 if(pagamento != null) { 
      out.write("\n");
      out.write("                    <div class=\"data-section\">\n");
      out.write("                        <h3>Metodo di Pagamento</h3>\n");
      out.write("                        <div class=\"data-item\">\n");
      out.write("                            <span class=\"data-label\">Metodo:</span>\n");
      out.write("                            <span class=\"data-value\">");
      out.print( pagamento.getMetodo() );
      out.write("</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"data-item\">\n");
      out.write("                            <span class=\"data-label\">Importo:</span>\n");
      out.write("                            <span class=\"data-value\">");
      out.print( String.format("%.2f", pagamento.getImporto()) );
      out.write(" €</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"data-item\">\n");
      out.write("                            <span class=\"data-label\">Data Pagamento:</span>\n");
      out.write("                            <span class=\"data-value\">");
      out.print( pagamento.getDataPagamento() );
      out.write("</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                <!-- Shipping Info -->\n");
      out.write("                ");
 if(spedizione != null) { 
      out.write("\n");
      out.write("                    <div class=\"data-section\">\n");
      out.write("                        <h3>Spedizione</h3>\n");
      out.write("                        <div class=\"data-item\">\n");
      out.write("                            <span class=\"data-label\">Metodo:</span>\n");
      out.write("                            <span class=\"data-value\">");
      out.print( spedizione.getMetodo() );
      out.write("</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"data-item\">\n");
      out.write("                            <span class=\"data-label\">Spese:</span>\n");
      out.write("                            <span class=\"data-value\">");
      out.print( String.format("%.2f", spedizione.getSpese()) );
      out.write(" €</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"data-item\">\n");
      out.write("                            <span class=\"data-label\">Data Consegna Prevista:</span>\n");
      out.write("                            <span class=\"data-value\">");
      out.print( spedizione.getDataConsegna() );
      out.write("</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                <!-- Footer Notes -->\n");
      out.write("                <div class=\"data-section\">\n");
      out.write("                    <div class=\"no-data-message\">\n");
      out.write("                        <p>Fattura emessa elettronicamente</p>\n");
      out.write("                        <p>Documento non valido ai fini fiscali</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Print Button -->\n");
      out.write("                <div class=\"btn-container\">\n");
      out.write("                    <button class=\"btn\" onclick=\"window.print()\">Stampa Fattura</button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
