/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-06-20 13:52:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.AdminAction;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import Control.TugurioSemplice.*;
import Model.*;
import Control.TugurioSemplice.Admin.*;
import java.util.*;
import Control.TugurioSemplice.*;
import Model.*;
import Control.TugurioSemplice.Admin.*;
import java.util.*;
import Control.TugurioSemplice.*;
import Model.*;
import Control.TugurioSemplice.Admin.*;

public final class DettagliUtente_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Home/header.jsp", Long.valueOf(1749934793000L));
    _jspx_dependants.put("/Home/footer.jsp", Long.valueOf(1749934775000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(10);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("Control.TugurioSemplice.Admin");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("Model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("Control.TugurioSemplice");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>Profilo Utente - Dettagli Cliente e Ordini</title>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"/TugurioSemplice/css/footer.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"/TugurioSemplice/css/scrollbar.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"/TugurioSemplice/css/Utente.css\">\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;700;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"it\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/header.css\">\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;400;700;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\n");
      out.write("        <title>TugurioSemplice - Home</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("    ");
 ClienteBean utente = (ClienteBean) session.getAttribute("user"); 
      out.write("\n");
      out.write("        <header class=\"menu\">\n");
      out.write("            <div class=\"top-bar\">\n");
      out.write("                <button class=\"mobile-menu\" aria-label=\"Toggle menu\">\n");
      out.write("                    <i class=\"fas fa-bars\"></i>\n");
      out.write("                    <i class=\"fas fa-times\"></i>\n");
      out.write("                </button>\n");
      out.write("                <span class=\"logo-text\">TUGURIOSEMPLICE</span>\n");
      out.write("                <a class=\"logo-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/logo.png\" alt=\"TugurioSemplice Logo\">\n");
      out.write("                </a>\n");
      out.write("                ");
 if(utente != null) { 
      out.write("\n");
      out.write("                <a class=\"login-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AuthSites/AreaUtente.jsp\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/Connesso.jpg\" alt=\"login\">\n");
      out.write("                </a>\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                <a class=\"login-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AccessoUtente/Login.jsp\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/access.png\" alt=\"login\">\n");
      out.write("                </a>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                <a class=\"cart-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart.jsp\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/cart.png\" alt=\"carrello\">\n");
      out.write("                </a>\n");
      out.write("            </div>  \n");
      out.write("            <nav id=\"main-nav\">  \n");
      out.write("    <a class=\"menu-item ");
      out.print( request.getRequestURI().contains("index.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">HOME</a>\n");
      out.write("    <a class=\"menu-item ");
      out.print( request.getRequestURI().contains("about.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/ChiSiamo.jsp\">CHI SIAMO</a>\n");
      out.write("    <a class=\"menu-item ");
      out.print( request.getRequestURI().contains("ProductView.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product\">CATALOGO</a>\n");
      out.write("    <a class=\"menu-item ");
      out.print( request.getRequestURI().contains("contact.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/Contatti.jsp\">CONTATTI</a>\n");
      out.write("    ");
 if(utente != null) { 
      out.write("\n");
      out.write("    <a class=\"menu-item mobile-only ");
      out.print( request.getRequestURI().contains("AreaUtente.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AreaUtente.jsp\">AREA UTENTE</a>\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("    <a class=\"menu-item mobile-only ");
      out.print( request.getRequestURI().contains("Login.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AuthSites/Login.jsp\">ACCEDI</a>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    <a class=\"menu-item mobile-only ");
      out.print( request.getRequestURI().contains("cart.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart.jsp\">CARRELLO</a>\n");
      out.write("</nav>\n");
      out.write("        </header>\n");
      out.write("        \n");
      out.write("        <script>\n");
      out.write("            document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("                const mobileMenuToggle = document.querySelector('.mobile-menu');\n");
      out.write("                const mainNav = document.getElementById('main-nav');\n");
      out.write("                \n");
      out.write("                mobileMenuToggle.addEventListener('click', function() {\n");
      out.write("                this.classList.toggle('active');\n");
      out.write("                mainNav.classList.toggle('mobile-active');\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("    </body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("        <div class=\"main-content\">\n");
      out.write("            <div class=\"main-container\">\n");
      out.write("                ");
 
                // Recupero il cliente dalla sessione
                ClienteBean cliente = (ClienteBean) session.getAttribute("Cliente");
                ArrayList<OrdineBean> listaOrdini = (ArrayList<OrdineBean>) session.getAttribute("listaOrdini");
                String dataInizioFiltro = (String) session.getAttribute("dataInizioFiltro");
                String dataFineFiltro = (String) session.getAttribute("dataFineFiltro");
                
      out.write("\n");
      out.write("                \n");
      out.write("                ");
 if(cliente != null) { 
      out.write("\n");
      out.write("                    <div class=\"page-header\">\n");
      out.write("                        <h1>Profilo Utente</h1>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"content\">\n");
      out.write("                        <div class=\"data-section\">\n");
      out.write("                            <h3>Informazioni Personali</h3>\n");
      out.write("                            <div class=\"data-item\">\n");
      out.write("                                <span class=\"data-label\">ID Cliente:</span>\n");
      out.write("                                <span class=\"data-value\">");
      out.print( cliente.getIdCliente() );
      out.write("</span>\n");
      out.write("                            </div>\n");
      out.write("                            ");
 if(cliente.getAnagrafia() != null) { 
      out.write("\n");
      out.write("                                <div class=\"data-item\">\n");
      out.write("                                    <span class=\"data-label\">Nome:</span>\n");
      out.write("                                    <span class=\"data-value\">");
      out.print( cliente.getAnagrafia().getNome() );
      out.write("</span>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"data-item\">\n");
      out.write("                                    <span class=\"data-label\">Cognome:</span>\n");
      out.write("                                    <span class=\"data-value\">");
      out.print( cliente.getAnagrafia().getCognome() );
      out.write("</span>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"data-item\">\n");
      out.write("                                    <span class=\"data-label\">Telefono:</span>\n");
      out.write("                                    <span class=\"data-value\">");
      out.print( cliente.getAnagrafia().getTelefono() != null ? cliente.getAnagrafia().getTelefono() : "N/D" );
      out.write("</span>\n");
      out.write("                                </div>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                            <div class=\"data-item\">\n");
      out.write("                                <span class=\"data-label\">Email:</span>\n");
      out.write("                                <span class=\"data-value\">");
      out.print( cliente.getEmail() );
      out.write("</span>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"data-item\">\n");
      out.write("                                <span class=\"data-label\">Admin:</span>\n");
      out.write("                                <span class=\"data-value\">");
      out.print( cliente.getIsAmministratore() ? "Sì" : "No" );
      out.write("</span>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"data-section\">\n");
      out.write("                            <h3>Indirizzo di Spedizione</h3>\n");
      out.write("                            ");
 if(cliente.getIndirizzoSpedizione() != null) { 
      out.write("\n");
      out.write("                                <div class=\"data-item\">\n");
      out.write("                                    <span class=\"data-label\">Via:</span>\n");
      out.write("                                    <span class=\"data-value\">");
      out.print( cliente.getIndirizzoSpedizione().getVia() != null ? cliente.getIndirizzoSpedizione().getVia() : "N/D" );
      out.write("</span>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"data-item\">\n");
      out.write("                                    <span class=\"data-label\">Città:</span>\n");
      out.write("                                    <span class=\"data-value\">");
      out.print( cliente.getIndirizzoSpedizione().getCitta() != null ? cliente.getIndirizzoSpedizione().getCitta() : "N/D" );
      out.write("</span>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"data-item\">\n");
      out.write("                                    <span class=\"data-label\">CAP:</span>\n");
      out.write("                                    <span class=\"data-value\">");
      out.print( cliente.getIndirizzoSpedizione().getCap() != null ? cliente.getIndirizzoSpedizione().getCap() : "N/D" );
      out.write("</span>\n");
      out.write("                                </div>\n");
      out.write("                            ");
 } else { 
      out.write("\n");
      out.write("                                <div class=\"no-data-message\">\n");
      out.write("                                    Nessun indirizzo di spedizione disponibile\n");
      out.write("                                </div>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"order-section\">\n");
      out.write("                            <h3>Ordini del Cliente</h3>\n");
      out.write("                            \n");
      out.write("                            <!-- Form per il filtro date -->\n");
      out.write("                            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ListaOrdineController\" method=\"post\" class=\"filters\" onsubmit=\"return validateDates()\">\n");
      out.write("                                <input type=\"hidden\" name=\"idCliente\" value=\"");
      out.print( cliente.getIdCliente() );
      out.write("\">\n");
      out.write("                                <input type=\"hidden\" value=\"AdminAction\" name=\"ADMIN\">\n");
      out.write("                                \n");
      out.write("                                <div>\n");
      out.write("                                    <label for=\"dataInizio\">Da:</label>\n");
      out.write("                                    <input type=\"date\" id=\"dataInizio\" name=\"dataInizio\" value=\"");
      out.print( dataInizioFiltro != null ? dataInizioFiltro : "" );
      out.write("\">\n");
      out.write("                                    \n");
      out.write("                                    <label for=\"dataFine\">A:</label>\n");
      out.write("                                    <input type=\"date\" id=\"dataFine\" name=\"dataFine\" value=\"");
      out.print( dataFineFiltro != null ? dataFineFiltro : "" );
      out.write("\">\n");
      out.write("                                    \n");
      out.write("                                    <button type=\"submit\">Filtra</button>\n");
      out.write("                                    <button type=\"button\" onclick=\"resetFilter()\">Svuota</button>\n");
      out.write("                                </div>\n");
      out.write("                                <div id=\"dateError\" class=\"error-message\" style=\"display:none; color:red;\"></div>\n");
      out.write("                            </form>\n");
      out.write("                            \n");
      out.write("                            ");
 
                            if(listaOrdini != null && !listaOrdini.isEmpty()) { 
                                for(OrdineBean ordine : listaOrdini) {
                            
      out.write("\n");
      out.write("                                <div class=\"order-subsection\">\n");
      out.write("                                    <h4>Ordine #");
      out.print( ordine.getIdOrdine() );
      out.write("</h4>\n");
      out.write("                                    <div class=\"data-item\">\n");
      out.write("                                        <span class=\"data-label\">Stato:</span>\n");
      out.write("                                        <span class=\"data-value\">");
      out.print( ordine.getStatoOrdine() );
      out.write("</span>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"data-item\">\n");
      out.write("                                        <span class=\"data-label\">Data Ordine:</span>\n");
      out.write("                                        <span class=\"data-value\">");
      out.print( ordine.getDataOrdine() );
      out.write("</span>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"data-item\">\n");
      out.write("                                        <span class=\"data-label\">Totale:</span>\n");
      out.write("                                        <span class=\"data-value\">");
      out.print( ordine.getPrezzoOrdine() );
      out.write(" €</span>\n");
      out.write("                                    </div>\n");
      out.write("                                    \n");
      out.write("                                    ");
 if(ordine.getPagamento() != null) { 
      out.write("\n");
      out.write("                                        <h4>Dettagli Pagamento</h4>\n");
      out.write("                                        <div class=\"data-item\">\n");
      out.write("                                            <span class=\"data-label\">Importo:</span>\n");
      out.write("                                            <span class=\"data-value\">");
      out.print( ordine.getPagamento().getImporto() );
      out.write(" €</span>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"data-item\">\n");
      out.write("                                            <span class=\"data-label\">Data Pagamento:</span>\n");
      out.write("                                            <span class=\"data-value\">");
      out.print( ordine.getPagamento().getDataPagamento() );
      out.write("</span>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"data-item\">\n");
      out.write("                                            <span class=\"data-label\">Metodo:</span>\n");
      out.write("                                            <span class=\"data-value\">");
      out.print( ordine.getPagamento().getMetodo() );
      out.write("</span>\n");
      out.write("                                        </div>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                    \n");
      out.write("                                    ");
 if(ordine.getSpedizione() != null) { 
      out.write("\n");
      out.write("                                        <h4>Dettagli Spedizione</h4>\n");
      out.write("                                        <div class=\"data-item\">\n");
      out.write("                                            <span class=\"data-label\">Metodo:</span>\n");
      out.write("                                            <span class=\"data-value\">");
      out.print( ordine.getSpedizione().getMetodo() );
      out.write("</span>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"data-item\">\n");
      out.write("                                            <span class=\"data-label\">Spese:</span>\n");
      out.write("                                            <span class=\"data-value\">");
      out.print( ordine.getSpedizione().getSpese() );
      out.write(" €</span>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"data-item\">\n");
      out.write("                                            <span class=\"data-label\">Data Consegna Prevista:</span>\n");
      out.write("                                            <span class=\"data-value\">");
      out.print( ordine.getSpedizione().getDataConsegna() );
      out.write("</span>\n");
      out.write("                                        </div>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                    \n");
      out.write("                                    ");
 if(ordine.getProdotti() != null && !ordine.getProdotti().isEmpty()) { 
      out.write("\n");
      out.write("                                        <h4>Prodotti Acquistati</h4>\n");
      out.write("                                        ");
 
                                        for(ProdottoOrdineBean prodotto : ordine.getProdotti()) {
                                            double subtotale = prodotto.getPrezzoBase() * prodotto.getQuantita();
                                        
      out.write("\n");
      out.write("                                            <div class=\"product-item\">\n");
      out.write("                                                <strong>");
      out.print( prodotto.getNome() );
      out.write("</strong> - ");
      out.print( prodotto.getPrezzoBase() );
      out.write(" € - Qtà: ");
      out.print( prodotto.getQuantita() );
      out.write(" - Subtotale: ");
      out.print( subtotale );
      out.write(" €\n");
      out.write("                                            </div>\n");
      out.write("                                        ");
 } 
      out.write("\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                </div>\n");
      out.write("                            ");
 
                                }
                            } else { 
                            
      out.write("\n");
      out.write("                                <div class=\"no-data-message\">\n");
      out.write("                                    ");
 if(dataInizioFiltro != null || dataFineFiltro != null) { 
      out.write("\n");
      out.write("                                        Nessun ordine trovato nel periodo selezionato.\n");
      out.write("                                    ");
 } else { 
      out.write("\n");
      out.write("                                        Il cliente non ha ancora effettuato ordini.\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                </div>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                    <div class=\"page-header\">\n");
      out.write("                        <h1>Errore</h1>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"content\">\n");
      out.write("                        <div class=\"no-data-message\">\n");
      out.write("                            Nessun cliente trovato nella sessione.\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"it\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/footer.css\">\n");
      out.write("		<link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;700;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("        <title>TugurioSemplice - Home</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("       <footer class=\"footer-container\">\n");
      out.write("    <div class=\"footer-links\">\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/ChiSiamo.jsp\" title=\"Informazioni su di noi\">Chi siamo</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/PrivacyPolicy.jsp\" title=\"La nostra politica sulla privacy\">Privacy Policy</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/TerminiCondizioni.jsp\" title=\"Termini del servizio\">Termini e Condizioni</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/Contatti.jsp\" title=\"Contattaci\">Contatti</a>\n");
      out.write("    </div>\n");
      out.write("    <p class=\"text copyright\">&copy; 2025 TugurioSemplice. Tutti i diritti riservati.</p>\n");
      out.write("</footer>\n");
      out.write("    </body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("    </body>\n");
      out.write("    <script>\n");
      out.write("        function resetFilter() {\n");
      out.write("            document.getElementById('dataInizio').value = '';\n");
      out.write("            document.getElementById('dataFine').value = '';\n");
      out.write("            document.forms[0].submit();\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function validateDates() {\n");
      out.write("            const dataInizio = document.getElementById('dataInizio').value;\n");
      out.write("            const dataFine = document.getElementById('dataFine').value;\n");
      out.write("            const errorElement = document.getElementById('dateError');\n");
      out.write("            \n");
      out.write("            if (dataInizio && dataFine && dataInizio > dataFine) {\n");
      out.write("                errorElement.textContent = \"La data di inizio deve essere precedente alla data di fine\";\n");
      out.write("                errorElement.style.display = 'block';\n");
      out.write("                return false;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            errorElement.style.display = 'none';\n");
      out.write("            return true;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        // Mostra messaggio se ci sono filtri attivi\n");
      out.write("        window.onload = function() {\n");
      out.write("            const dataInizio = \"");
      out.print( dataInizioFiltro != null ? dataInizioFiltro : "" );
      out.write("\";\n");
      out.write("            const dataFine = \"");
      out.print( dataFineFiltro != null ? dataFineFiltro : "" );
      out.write("\";\n");
      out.write("            \n");
      out.write("            if(dataInizio || dataFine) {\n");
      out.write("                const filterInfo = document.createElement('div');\n");
      out.write("                filterInfo.className = 'filter-info';\n");
      out.write("                filterInfo.innerHTML = 'Filtro attivo: ' + \n");
      out.write("                    (dataInizio ? 'Dal ' + dataInizio : '') + \n");
      out.write("                    (dataFine ? (dataInizio ? ' al ' : 'Fino al ') + dataFine : '');\n");
      out.write("                document.querySelector('.order-section').insertBefore(filterInfo, document.querySelector('.order-section h3').nextSibling);\n");
      out.write("            }\n");
      out.write("        };\n");
      out.write("    </script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
