/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-06-18 06:58:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.AdminAction;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import Control.TugurioSemplice.*;
import Model.*;
import Control.TugurioSemplice.Admin.*;

public final class InsertAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(10);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("Control.TugurioSemplice.Admin");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("Model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("Control.TugurioSemplice");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("	<head>\n");
      out.write("		<meta charset=\"UTF-8\">\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/screen.css\">\n");
      out.write("		<link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;700;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("		<title>Inserimento Prodotto</title>\n");
      out.write("		<style>	\n");
      out.write("			textarea, input[type=\"number\"], input[type=\"file\"] {\n");
      out.write("			    width: 100%;\n");
      out.write("			    padding: clamp(0.5rem, 2vw, 0.75rem);\n");
      out.write("			    border: 1px solid #ddd;\n");
      out.write("			    border-radius: 0.25rem;\n");
      out.write("			    box-sizing: border-box;\n");
      out.write("			    font-family: 'Josefin Sans', sans-serif;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			textarea {\n");
      out.write("			    resize: vertical;\n");
      out.write("			    min-height: 80px;\n");
      out.write("			}\n");
      out.write("			/*Chrome/Safari*/\n");
      out.write("			input[type=\"file\"]::-webkit-file-upload-button {\n");
      out.write("			    background-color: #74292c;\n");
      out.write("			    color: white;\n");
      out.write("			    border: none;\n");
      out.write("			    border-radius: 0.25rem;\n");
      out.write("			    padding: 0.5rem 1rem;\n");
      out.write("			    font-family: 'Josefin Sans', sans-serif;\n");
      out.write("			    cursor: pointer;\n");
      out.write("			    margin-right: 0.5rem;\n");
      out.write("			    transition: opacity 0.3s ease;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			input[type=\"file\"]::-webkit-file-upload-button:hover {\n");
      out.write("			    opacity: 0.7;\n");
      out.write("			}\n");
      out.write("			/* Per Firefox */\n");
      out.write("			input[type=\"file\"]::file-selector-button {\n");
      out.write("			    background-color: #74292c;\n");
      out.write("			    color: white;\n");
      out.write("			    border: none;\n");
      out.write("			    border-radius: 0.25rem;\n");
      out.write("			    padding: 0.5rem 1rem;\n");
      out.write("			    font-family: 'Josefin Sans', sans-serif;\n");
      out.write("			    cursor: pointer;\n");
      out.write("			    margin-right: 0.5rem;\n");
      out.write("			    transition: opacity 0.3s ease;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			input[type=\"file\"]::file-selector-button:hover {\n");
      out.write("			    opacity: 0.7;\n");
      out.write("			}\n");
      out.write("		</style>\n");
      out.write("	</head>\n");
      out.write("	<body>\n");
      out.write("		<img src=\"/TugurioSemplice/photo/logo.png\" alt=\"logo\" class=\"logo\">\n");
      out.write("		\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<h2>Inserimento il prodotto</h2>\n");
      out.write("			<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/InsertProductController\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("				\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<label for=\"name\">Nome:</label>\n");
      out.write("					<input type=\"text\" name=\"name\" id=\"name\" required>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<label for=\"description\">Descrizione:</label>\n");
      out.write("					<textarea name=\"description\" id=\"description\" rows=\"3\" required></textarea>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<label for=\"price\">Prezzo Base:</label>\n");
      out.write("					<input type=\"number\" name=\"price\" id=\"price\" min=\"0\" step=\"0.01\" required>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<label for=\"quantity\">Quantità:</label>\n");
      out.write("					<input type=\"number\" name=\"quantity\" id=\"quantity\" min=\"0\" required>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<label for=\"image\">Immagine:</label>\n");
      out.write("					<input type=\"file\" name=\"image\" id=\"image\" required>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<button type=\"submit\" class=\"submit-btn\">Aggiungi Prodotto</button>\n");
      out.write("			</form>\n");
      out.write("		</div>\n");
      out.write("	</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
