/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-06-21 13:18:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.AdminAction;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import Control.TugurioSemplice.*;
import Model.*;
import Control.TugurioSemplice.Admin.*;
import java.util.*;
import Control.TugurioSemplice.*;
import Model.*;
import Control.TugurioSemplice.Admin.*;
import java.util.*;
import Control.TugurioSemplice.*;
import Model.*;
import Control.TugurioSemplice.Admin.*;

public final class ListaUtenti_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Home/header.jsp", Long.valueOf(1749934793000L));
    _jspx_dependants.put("/Home/footer.jsp", Long.valueOf(1749934775000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(10);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("Control.TugurioSemplice.Admin");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("Model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("Control.TugurioSemplice");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"/TugurioSemplice/css/footer.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"/TugurioSemplice/css/scrollbar.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"/TugurioSemplice/css/Utente.css\">\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;700;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("        <title>Lista degli utenti</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"it\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/header.css\">\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;400;700;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\n");
      out.write("        <title>TugurioSemplice - Home</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("    ");
 ClienteBean utente = (ClienteBean) session.getAttribute("user"); 
      out.write("\n");
      out.write("        <header class=\"menu\">\n");
      out.write("            <div class=\"top-bar\">\n");
      out.write("                <button class=\"mobile-menu\" aria-label=\"Toggle menu\">\n");
      out.write("                    <i class=\"fas fa-bars\"></i>\n");
      out.write("                    <i class=\"fas fa-times\"></i>\n");
      out.write("                </button>\n");
      out.write("                <span class=\"logo-text\">TUGURIOSEMPLICE</span>\n");
      out.write("                <a class=\"logo-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/logo.png\" alt=\"TugurioSemplice Logo\">\n");
      out.write("                </a>\n");
      out.write("                ");
 if(utente != null) { 
      out.write("\n");
      out.write("                <a class=\"login-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AuthSites/AreaUtente.jsp\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/Connesso.jpg\" alt=\"login\">\n");
      out.write("                </a>\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                <a class=\"login-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AccessoUtente/Login.jsp\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/access.png\" alt=\"login\">\n");
      out.write("                </a>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                <a class=\"cart-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart.jsp\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/photo/cart.png\" alt=\"carrello\">\n");
      out.write("                </a>\n");
      out.write("            </div>  \n");
      out.write("            <nav id=\"main-nav\">  \n");
      out.write("    <a class=\"menu-item ");
      out.print( request.getRequestURI().contains("index.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">HOME</a>\n");
      out.write("    <a class=\"menu-item ");
      out.print( request.getRequestURI().contains("about.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/ChiSiamo.jsp\">CHI SIAMO</a>\n");
      out.write("    <a class=\"menu-item ");
      out.print( request.getRequestURI().contains("ProductView.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product\">CATALOGO</a>\n");
      out.write("    <a class=\"menu-item ");
      out.print( request.getRequestURI().contains("contact.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/Contatti.jsp\">CONTATTI</a>\n");
      out.write("    ");
 if(utente != null) { 
      out.write("\n");
      out.write("    <a class=\"menu-item mobile-only ");
      out.print( request.getRequestURI().contains("AreaUtente.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AreaUtente.jsp\">AREA UTENTE</a>\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("    <a class=\"menu-item mobile-only ");
      out.print( request.getRequestURI().contains("Login.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AuthSites/Login.jsp\">ACCEDI</a>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    <a class=\"menu-item mobile-only ");
      out.print( request.getRequestURI().contains("cart.jsp") ? "active" : "" );
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart.jsp\">CARRELLO</a>\n");
      out.write("</nav>\n");
      out.write("        </header>\n");
      out.write("        \n");
      out.write("        <script>\n");
      out.write("            document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("                const mobileMenuToggle = document.querySelector('.mobile-menu');\n");
      out.write("                const mainNav = document.getElementById('main-nav');\n");
      out.write("                \n");
      out.write("                mobileMenuToggle.addEventListener('click', function() {\n");
      out.write("                this.classList.toggle('active');\n");
      out.write("                mainNav.classList.toggle('mobile-active');\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("    </body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("        \n");
      out.write("        <div class=\"main-content\">\n");
      out.write("            <div class=\"main-container\">\n");
      out.write("                <div class=\"page-header\">\n");
      out.write("                    <h1>Lista Utenti</h1>\n");
      out.write("                    <div class=\"filters\">\n");
      out.write("                        <form action=\"ListaUtentiController\" method=\"get\" class=\"search-form\">\n");
      out.write("                            <div class=\"search-container\">\n");
      out.write("                                <input type=\"text\" list=\"search-suggestions\" placeholder=\"Cerca utenti...\" name=\"q\" id=\"search-input\" autocomplete=\"off\"/>\n");
      out.write("                                <datalist id=\"search-suggestions\"></datalist>\n");
      out.write("                                <button type=\"submit\" class=\"search-btn\">\n");
      out.write("                                    <svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n");
      out.write("                                        <circle cx=\"11\" cy=\"11\" r=\"8\"/>\n");
      out.write("                                        <path d=\"m21 21-4.35-4.35\"/>\n");
      out.write("                                    </svg>\n");
      out.write("                                </button>\n");
      out.write("                            </div>\n");
      out.write("                        </form>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"content\">\n");
      out.write("                    ");
 
                        ArrayList<ClienteBean> lista = (ArrayList<ClienteBean>) request.getAttribute("Clienti");
                        if(lista != null && !lista.isEmpty()) {
                    
      out.write("\n");
      out.write("                        ");
 for(ClienteBean cliente : lista) { 
      out.write("\n");
      out.write("                            <div class=\"user-card\">\n");
      out.write("                                <h3>Cliente #");
      out.print( cliente.getIdCliente() );
      out.write("</h3>\n");
      out.write("                                <div class=\"user-info\">\n");
      out.write("                                    <div class=\"data-item\">\n");
      out.write("                                        <span class=\"data-label\">Nome:</span>\n");
      out.write("                                        <span class=\"data-value\">");
      out.print( cliente.getAnagrafia().getNome() );
      out.write("</span>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"data-item\">\n");
      out.write("                                        <span class=\"data-label\">Cognome:</span>\n");
      out.write("                                        <span class=\"data-value\">");
      out.print( cliente.getAnagrafia().getCognome() );
      out.write("</span>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"data-item\">\n");
      out.write("                                        <span class=\"data-label\">Email:</span>\n");
      out.write("                                        <span class=\"data-value\">");
      out.print( cliente.getEmail() );
      out.write("</span>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"user-actions\">\n");
      out.write("                                    <form action=\"ListaOrdineController\" method=\"post\" style=\"display: inline;\">\n");
      out.write("                                        <input type=\"hidden\" value=\"");
      out.print( cliente.getIdCliente());
      out.write("\" name=\"idCliente\">\n");
      out.write("                                        <input type=\"hidden\" value=\"AdminAction\" name=\"ADMIN\">\n");
      out.write("                                        <button type=\"submit\" class=\"btn\">Dettagli Cliente</button>\n");
      out.write("                                    </form>\n");
      out.write("                                    <form action=\"DeleteUtenteController\" method=\"post\" style=\"display: inline;\" onsubmit=\"return confirmDelete()\">\n");
      out.write("                                        <input type=\"hidden\" value=\"");
      out.print( cliente.getIdCliente());
      out.write("\" name=\"id\">\n");
      out.write("                                        ");
 if(utente.getIdCliente() != cliente.getIdCliente()) { 
      out.write("\n");
      out.write("                                            <button type=\"submit\" class=\"btn\">Elimina Cliente</button>\n");
      out.write("                                        ");
 } else { 
      out.write("\n");
      out.write("                                            <button type=\"button\" class=\"btn\" disabled title=\"Non puoi eliminare te stesso\">Elimina Cliente</button>\n");
      out.write("                                        ");
 } 
      out.write("\n");
      out.write("                                    </form>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                    ");

                        } else {
                    
      out.write("\n");
      out.write("                        <div class=\"no-data-message\">\n");
      out.write("                            <p>Nessun utente registrato</p>\n");
      out.write("                        </div>\n");
      out.write("                    ");

                        }
                    
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"it\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/footer.css\">\n");
      out.write("		<link href=\"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;700;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("        <title>TugurioSemplice - Home</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("       <footer class=\"footer-container\">\n");
      out.write("    <div class=\"footer-links\">\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/ChiSiamo.jsp\" title=\"Informazioni su di noi\">Chi siamo</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/PrivacyPolicy.jsp\" title=\"La nostra politica sulla privacy\">Privacy Policy</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/TerminiCondizioni.jsp\" title=\"Termini del servizio\">Termini e Condizioni</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Home/Contatti.jsp\" title=\"Contattaci\">Contatti</a>\n");
      out.write("    </div>\n");
      out.write("    <p class=\"text copyright\">&copy; 2025 TugurioSemplice. Tutti i diritti riservati.</p>\n");
      out.write("</footer>\n");
      out.write("    </body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("        <script>\n");
      out.write("            function confirmDelete() {\n");
      out.write("                return confirm('Sei sicuro di voler eliminare questo utente? Questa azione non può essere annullata.');\n");
      out.write("            }\n");
      out.write("        </script>\n");
      out.write("        <script>\n");
      out.write("            document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("                const searchInput = document.getElementById('search-input');\n");
      out.write("                const datalist = document.getElementById('search-suggestions');\n");
      out.write("                let lastQuery = '';\n");
      out.write("                let debounceTimer;\n");
      out.write("            \n");
      out.write("                searchInput.addEventListener('input', function() {\n");
      out.write("                    const query = this.value.trim();\n");
      out.write("                    \n");
      out.write("                    clearTimeout(debounceTimer);\n");
      out.write("                    \n");
      out.write("                    if(query.length >= 2 && query !== lastQuery) {\n");
      out.write("                        searchInput.setAttribute('data-loading', 'true');\n");
      out.write("                        \n");
      out.write("                        debounceTimer = setTimeout(() => {\n");
      out.write("                            fetch('RicercaUtente?q=' + encodeURIComponent(query))\n");
      out.write("                                .then(response => {\n");
      out.write("                                    if(!response.ok) throw new Error('Network response was not ok');\n");
      out.write("                                    return response.json();\n");
      out.write("                                })\n");
      out.write("                                .then(data => {\n");
      out.write("                                    datalist.innerHTML = '';\n");
      out.write("                                    \n");
      out.write("                                    if(data && data.length > 0) {\n");
      out.write("                                        data.forEach(item => {\n");
      out.write("                                            const option = document.createElement('option');\n");
      out.write("                                            option.value = item;\n");
      out.write("                                            datalist.appendChild(option);\n");
      out.write("                                        });\n");
      out.write("                                    }\n");
      out.write("                                    \n");
      out.write("                                    lastQuery = query;\n");
      out.write("                                })\n");
      out.write("                                .catch(error => {\n");
      out.write("                                    console.error('Error:', error);\n");
      out.write("                                    datalist.innerHTML = '';\n");
      out.write("                                })\n");
      out.write("                                .finally(() => {\n");
      out.write("                                    searchInput.removeAttribute('data-loading');\n");
      out.write("                                });\n");
      out.write("                        }, 200);\n");
      out.write("                    } else if(query.length < 2) {\n");
      out.write("                        datalist.innerHTML = '';\n");
      out.write("                        lastQuery = '';\n");
      out.write("                    }\n");
      out.write("                });\n");
      out.write("            \n");
      out.write("                searchInput.addEventListener('blur', function() {\n");
      out.write("                    setTimeout(() => {\n");
      out.write("                        datalist.innerHTML = '';\n");
      out.write("                    }, 200);\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
